worker_processes auto;

events {}

http {
    resolver 8.8.8.8 8.8.4.4 valid=300s ipv6=off;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream viper {
        server cegeb.mindfreak.online:443;
        server aahol.mindfreak.online:443;
        server urywk.mindfreak.online:443;
    }

    server {
        listen 8080;

        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;

        location /ssh {
            proxy_pass https://viper/ssh;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Target-Protocol ssh;
            proxy_ssl_server_name on;
            proxy_ssl_verify off;
        }

        location /ovpn {
            proxy_pass https://viper/ovpn;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Target-Protocol openvpn;
            proxy_ssl_server_name on;
            proxy_ssl_verify off;
        }

        location /vless {
            proxy_pass https://viper/vless;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Target-Protocol tls;
            proxy_ssl_server_name on;
            proxy_ssl_verify off;
        }

        location /vmess {
            proxy_pass https://viper/vmess;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $host;
            proxy_set_header X-Target-Protocol tls;
            proxy_ssl_server_name on;
            proxy_ssl_verify off;
        }

        location / {
            return 404;
        }
    }
}
